training_path = 'data/train'
validation_path = 'data/validate'
load_weights_from = 'check/d.h5'
model_number = 4
dataset_path = 'raw/*'
shuffle_buffer_size = 1000
batch_size = 16
validation_frac = 0.2
file_include_times = 5
hint_points_prob = 1.0 / 10.0
hint_sample_variance = 9
expose_everything_frac = 0.05
image_height = 224
image_width = 224
epochs_count = 30
hint_radius = 5
