training_path = 'data/active'
validation_path = 'data/active'
load_weights_from = None
model_number = 6
dataset_path = 'raw/*'
shuffle_buffer_size = 1000
data_batch_size = 1
train_batch_size = 16
validation_frac = 0.2
file_include_times = 1
hint_points_prob = 1.0 / 10.0
hint_sample_variance = 9
expose_everything_frac = 0.05
image_height = 224
image_width = 224
epochs_count = 50
hint_radius = 5
